apiVersion: v1
kind: Pod
metadata:
  name: my-kuar-pod
  labels:
    company: practice2
    role: rg-role
spec:
  containers:
    - name: my-kuar
      image: gcr.io/kuar-demo/kuard-amd64:1
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "250Mi"
          cpu: "500m"
