apiVersion: v1
kind: Pod
metadata:
  name: my-mysql-pod
  labels:
    practice: practice2
    role: rg-role
spec:
  containers:
    - name: my-mysql
      image: mysql:5
      env:
        - name: "MYSQL_USER"
          value: "mysql"
        - name: "MYSQL_PASSWORD"
          value: "mysql"
        - name: "MYSQL_DATABASE"
          value: "testdb"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "root"
      ports:
        - containerPort: 3306
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "800Mi"
          cpu: "800m"
