apiVersion: v1
kind: Pod
metadata:
  name: my-postgres-pod
  labels:
    practice: practice2
    role: rg-role
spec:
  containers:
    - name: my-postgres
      image: postgres:alpine
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: my-db
        - name: POSTGRES_USER
          value: my-user
        - name: POSTGRES_PASSWORD
          value: postgres
