apiVersion: v1
kind: Pod
metadata:
  name: my-redis-pod
  namespace: dev
  labels:
    practice: practice2
    environment: dev
spec:
  containers:
    - name: my-redis
      image: redis:latest
      ports:
        - containerPort: 6379
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "250Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-redis-pod
  namespace: test
  labels:
    practice: practice2
    environment: test
spec:
  containers:
    - name: my-redis
      image: redis:latest
      ports:
        - containerPort: 6379
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "250Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-redis-pod
  namespace: prod
  labels:
    practice: practice2
    environment: prod
spec:
  containers:
    - name: my-redis
      image: redis:latest
      ports:
        - containerPort: 6379
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "250Mi"
          cpu: "500m"